version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webacsc-app

    restart: unless-stopped

    environment:
      SERVER_PORT: 3000
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL:-jdbc:postgresql://10.142.0.7:5520/dashboard_db}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME:-postgres}
      SPRING_DATASOURCE_PASSWORD: User*2018
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
      APP_JWT_SECRET: ${APP_JWT_SECRET:-bXlfc3VwZXJfc2VjcmV0X2tleV8zMl9ieXRlc19taW5pbW9fYmFzZTY0X3Rlc3Q=}
      APP_JWT_EXPIRATION_MS: ${APP_JWT_EXPIRATION_MS:-86400000}
      APP_APK_RESOURCE_PATH: ${APP_APK_RESOURCE_PATH:-file:/app/apk/acsc.apk}
      APP_APK_DOWNLOAD_NAME: ${APP_APK_DOWNLOAD_NAME:-acsc.apk}

    ports:
      - "3000:3000"

    volumes:
      - ./apk:/app/apk:ro

    extra_hosts:
      - "desarrollo.compuconta.com:10.142.0.7"
      - "host.docker.internal:host-gateway"